// Banques de phrases et de réponses de bots. Ajoute tes propres phrases ici.

const PROMPTS_CLASSIQUE = [
  "Plus c'est long, plus c'est bon.",
  "Il faut bien le secouer avant usage.",
  "Ça rentre mieux avec un peu de salive.",
  "C'est mieux à deux, mais seul ça dépanne.",
  "Il faut souffler dessus pour que ça marche.",
  "Quand c'est dur, c'est prêt.",
  "Plus tu frottes, plus ça chauffe.",
  "On le prend en bouche et on souffle fort.",
  "Ça gonfle quand on s'en occupe bien.",
  "Il vaut mieux mettre une protection avant.",
  "On le met dedans, on le ressort, on recommence.",
  "C'est tout mouillé quand on a fini.",
  "Il faut la tenir fermement par le manche.",
  "Ça se fait souvent le dimanche matin.",
  "On a du mal à le faire tenir debout.",
  "Il faut bien lécher avant de fermer.",
  "Ça gicle partout si on appuie trop fort.",
  "On se met à genoux pour mieux faire.",
  "Il adore qu'on lui gratte le ventre.",
  "Ça passe tout seul quand c'est bien lubrifié.",
  "On l'a tous fait dans la voiture au moins une fois.",
  "Ça dure trois minutes et tout le monde est content.",
  "Il faut enlever l'emballage avant de commencer.",
  "Plus c'est gros, plus c'est dur à avaler.",
  "On le fait par derrière, c'est plus pratique.",
  "Il faut attendre qu'elle soit bien chaude.",
  "On tire un coup et on recommence.",
  "Ça vibre dans la poche.",
  "Il sort tout seul quand c'est prêt.",
  "On monte, on descend, jusqu'à épuisement.",
  "On le fait à quatre pattes sous le lit.",
  "Il faut le tremper avant de le mettre dans la bouche.",
  "Ouvre grand, ça ne fera pas mal.",
  "On en redemande même avec mal aux jambes.",
  "C'est toujours meilleur quand ça dégouline.",
  "Il faut pomper fort pour qu'il se relève.",
  "On y met un doigt pour vérifier si c'est prêt.",
  "Ça s'allonge quand on tire dessus.",
  "Doucement au début, puis de plus en plus vite.",
  "On le fait en cachette de ses parents.",
  "Plus on s'agite, plus ça mousse.",
  "Il faut viser juste, sinon ça fait des dégâts.",
  "Deux boules, c'est le minimum.",
  "On le suce jusqu'au bâton.",
  "Ça rentre tout juste, il faut forcer un peu.",
  "On le chevauche pendant des heures.",
  "C'est tout doux, tout poilu et ça ronronne.",
  "On s'assoit dessus et on se laisse aller.",
  "Il faut bien remuer pour que ça épaississe.",
  "On le fait debout sous la douche.",
  "Tout le monde a crié quand il est sorti.",
  "Ça fait crac quand on force trop."
];

const PROMPTS_ABSURDE = [
  "Ce qu'un pingouin cache dans son frigo.",
  "La vraie raison pour laquelle les chaussettes disparaissent.",
  "Le 11e commandement, oublié en route.",
  "Ce que ton grille-pain pense de toi.",
  "Le pire nom pour un cheval de course.",
  "Ce qu'on trouve dans la poche d'un fantôme.",
  "La nouvelle épreuve olympique de 2040.",
  "Ce que murmurent les plantes vertes la nuit.",
  "Le parfum de glace que personne n'a demandé.",
  "Le métier secret des pigeons.",
  "L'avis Google d'un extraterrestre sur la Terre.",
  "L'objet le plus inutile à emporter sur une île déserte.",
  "Le slogan d'un dentifrice pour vampires.",
  "Ce que le chat fait pendant que tu dors.",
  "Le titre du prochain best-seller de ta belle-mère.",
  "La phrase à ne jamais dire à un dragon.",
  "Ce que contient vraiment la boîte noire d'un avion.",
  "Le super-pouvoir le plus décevant.",
  "Le nom du groupe de rock formé par des légumes.",
  "Ce que les escargots se racontent à la pause.",
  "Le pire cadeau de mariage.",
  "L'excuse de retard qui marche à tous les coups.",
  "Le plat signature d'un restaurant pour robots.",
  "La matière enseignée le vendredi à l'école des sorcières.",
  "Ce qu'on entend dans un coquillage si on écoute vraiment bien.",
  "Le premier message posté par un dinosaure.",
  "La règle secrète du Monopoly.",
  "Ce que ton frigo fait quand tu fermes la porte.",
  "L'application que personne ne télécharge.",
  "La vraie couleur du ciel le mardi."
];

const BOT_ANSWERS = ["Une enceinte", "Un hamster", "Mon oncle", "Une pile", "Le Wi-Fi", "Un piment", "Une fourmi", "Un aspirateur", "Un expresso", "Une chaussette", "Un grille-pain", "Le lundi", "Un raton laveur", "Une trottinette", "Le fromage", "Un parapluie", "Le chauffage", "Un pigeon", "La télécommande", "Un moustique", "Une glace", "Un sachet de thé", "Une poêle", "Un matelas gonflable", "Une enveloppe"];
const BOT_ABSURD = ["Une licorne en redressement fiscal", "Trois pigeons dans un imper", "Du Wi-Fi en poudre", "Un raton laveur ministre", "La moustache de Mamie", "Un yaourt qui a vu des choses", "Des chaussettes en grève", "Un canapé qui juge", "Le fantôme d'un croissant", "Une baguette ceinture noire"];
const BOT_NAMES = ["Robot Gérard", "Bip-Bop", "Tata Algo", "Monsieur Pixel", "Zinzin 3000", "Carla Bug", "Octet", "Gaston.exe"];

module.exports = { PROMPTS_CLASSIQUE, PROMPTS_ABSURDE, BOT_ANSWERS, BOT_ABSURD, BOT_NAMES };
