// Banques de phrases et de réponses de bots. Ajoute tes propres phrases ici.

const PROMPTS_CLASSIQUE = [
  "Il est petit, mais étonnamment puissant.",
  "On l'utilise tous les jours sans jamais le remercier.",
  "Ça fait du bruit la nuit.",
  "Mieux vaut ne pas le laisser trop longtemps au soleil.",
  "On le perd toujours au pire moment.",
  "Il faut le secouer avant de l'utiliser.",
  "Plus il vieillit, plus il a de la valeur.",
  "Ça se gonfle et ça se dégonfle.",
  "On le partage rarement de bon cœur.",
  "Ça sent fort, mais on s'y habitue.",
  "Il suffit d'appuyer au bon endroit.",
  "On l'attend avec impatience, puis on regrette.",
  "C'est doux à l'extérieur et dur à l'intérieur.",
  "Tout le monde en a un, personne ne l'avoue.",
  "Ça coule quand il ne faut pas.",
  "On le cache au fond du tiroir.",
  "Il tourne en rond toute la journée.",
  "Ça pique si on s'y prend mal.",
  "Il ne sert qu'une fois par an.",
  "On le fait durer le plus longtemps possible.",
  "Ça gratte un peu au début.",
  "Il change de couleur quand il chauffe.",
  "On le montre fièrement à ses amis.",
  "Ça tient dans la main, mais ça coûte une fortune.",
  "Il faut être deux pour bien le faire.",
  "On le trouve souvent sous le canapé.",
  "Ça rentre, mais de justesse.",
  "Il vaut mieux le faire avant de dormir.",
  "Ça se mange froid, de préférence.",
  "Il a mauvaise réputation, mais tout le monde l'adore.",
  "On l'entend avant de le voir.",
  "Il faut le nourrir régulièrement.",
  "Ça colle aux doigts.",
  "Il est long, fin et toujours dans le passage.",
  "On le range, il revient.",
  "Ça fait mal, mais ça fait du bien.",
  "Il se lève avant tout le monde.",
  "On le tire d'un coup sec.",
  "Ça ne marche jamais du premier coup.",
  "Il est plein de trous et pourtant utile.",
  "On le garde pour les grandes occasions.",
  "Ça brille dans le noir.",
  "Il faut le tenir fermement.",
  "Ça part en fumée.",
  "On le cherche partout alors qu'il est dans ta poche.",
  "Il a une drôle d'odeur le lundi matin.",
  "Ça se glisse discrètement dans le sac.",
  "Il fait peur aux enfants et aux chats.",
  "On le vide, on le remplit, on recommence.",
  "Il a beaucoup de dents mais ne mord jamais."
];

const PROMPTS_ABSURDE = [
  "Ce qu'un pingouin cache dans son frigo.",
  "La vraie raison pour laquelle les chaussettes disparaissent.",
  "Le 11e commandement, oublié en route.",
  "Ce que ton grille-pain pense de toi.",
  "Le pire nom pour un cheval de course.",
  "Ce qu'on trouve dans la poche d'un fantôme.",
  "La nouvelle épreuve olympique de 2040.",
  "Ce que murmurent les plantes vertes la nuit.",
  "Le parfum de glace que personne n'a demandé.",
  "Le métier secret des pigeons.",
  "L'avis Google d'un extraterrestre sur la Terre.",
  "L'objet le plus inutile à emporter sur une île déserte.",
  "Le slogan d'un dentifrice pour vampires.",
  "Ce que le chat fait pendant que tu dors.",
  "Le titre du prochain best-seller de ta belle-mère.",
  "La phrase à ne jamais dire à un dragon.",
  "Ce que contient vraiment la boîte noire d'un avion.",
  "Le super-pouvoir le plus décevant.",
  "Le nom du groupe de rock formé par des légumes.",
  "Ce que les escargots se racontent à la pause.",
  "Le pire cadeau de mariage.",
  "L'excuse de retard qui marche à tous les coups.",
  "Le plat signature d'un restaurant pour robots.",
  "La matière enseignée le vendredi à l'école des sorcières.",
  "Ce qu'on entend dans un coquillage si on écoute vraiment bien.",
  "Le premier message posté par un dinosaure.",
  "La règle secrète du Monopoly.",
  "Ce que ton frigo fait quand tu fermes la porte.",
  "L'application que personne ne télécharge.",
  "La vraie couleur du ciel le mardi."
];

const BOT_ANSWERS = ["Une enceinte", "Un hamster", "Mon oncle", "Une pile", "Le Wi-Fi", "Un piment", "Une fourmi", "Un aspirateur", "Un expresso", "Une chaussette", "Un grille-pain", "Le lundi", "Un raton laveur", "Une trottinette", "Le fromage", "Un parapluie", "Le chauffage", "Un pigeon", "La télécommande", "Un moustique"];
const BOT_ABSURD = ["Une licorne en redressement fiscal", "Trois pigeons dans un imper", "Du Wi-Fi en poudre", "Un raton laveur ministre", "La moustache de Mamie", "Un yaourt qui a vu des choses", "Des chaussettes en grève", "Un canapé qui juge", "Le fantôme d'un croissant", "Une baguette ceinture noire"];
const BOT_NAMES = ["Robot Gérard", "Bip-Bop", "Tata Algo", "Monsieur Pixel", "Zinzin 3000", "Carla Bug", "Octet", "Gaston.exe"];

module.exports = { PROMPTS_CLASSIQUE, PROMPTS_ABSURDE, BOT_ANSWERS, BOT_ABSURD, BOT_NAMES };
