// Banques de phrases et de réponses de bots. Ajoute tes propres phrases ici.

const PROMPTS_CLASSIQUE = [
  "Plus c'est long, plus c'est bon.",
  "Il faut bien le secouer avant usage.",
  "Ça rentre mieux avec un peu de salive.",
  "C'est mieux à deux, mais seul ça dépanne.",
  "Il faut souffler dessus pour que ça marche.",
  "Quand c'est dur, c'est prêt.",
  "Plus tu frottes, plus ça chauffe.",
  "On le prend en bouche et on souffle fort.",
  "Ça gonfle quand on s'en occupe bien.",
  "Il vaut mieux mettre une protection avant.",
  "On le met dedans, on le ressort, on recommence.",
  "C'est tout mouillé quand on a fini.",
  "Il faut la tenir fermement par le manche.",
  "Ça se fait souvent le dimanche matin.",
  "On a du mal à le faire tenir debout.",
  "Il faut bien lécher avant de fermer.",
  "Ça gicle partout si on appuie trop fort.",
  "On se met à genoux pour mieux faire.",
  "Il adore qu'on lui gratte le ventre.",
  "Ça passe tout seul quand c'est bien lubrifié.",
  "On l'a tous fait dans la voiture au moins une fois.",
  "Ça dure trois minutes et tout le monde est content.",
  "Il faut enlever l'emballage avant de commencer.",
  "Plus c'est gros, plus c'est dur à avaler.",
  "On le fait par derrière, c'est plus pratique.",
  "Il faut attendre qu'elle soit bien chaude.",
  "On tire un coup et on recommence.",
  "Ça vibre dans la poche.",
  "Il sort tout seul quand c'est prêt.",
  "On monte, on descend, jusqu'à épuisement.",
  "On le fait à quatre pattes sous le lit.",
  "Il faut le tremper avant de le mettre dans la bouche.",
  "Ouvre grand, ça ne fera pas mal.",
  "On en redemande même avec mal aux jambes.",
  "C'est toujours meilleur quand ça dégouline.",
  "Il faut pomper fort pour qu'il se relève.",
  "On y met un doigt pour vérifier si c'est prêt.",
  "Ça s'allonge quand on tire dessus.",
  "Doucement au début, puis de plus en plus vite.",
  "On le fait en cachette de ses parents.",
  "Plus on s'agite, plus ça mousse.",
  "Il faut viser juste, sinon ça fait des dégâts.",
  "Deux boules, c'est le minimum.",
  "On le suce jusqu'au bâton.",
  "Ça rentre tout juste, il faut forcer un peu.",
  "On le chevauche pendant des heures.",
  "C'est tout doux, tout poilu et ça ronronne.",
  "On s'assoit dessus et on se laisse aller.",
  "Il faut bien remuer pour que ça épaississe.",
  "On le fait debout sous la douche.",
  "Tout le monde a crié quand il est sorti.",
  "Ça fait crac quand on force trop.",
  "Il faut bien l'huiler pour que ça glisse.",
  "On le prend à pleine main et on serre fort.",
  "Ça durcit quand il fait froid.",
  "Plus on le caresse, plus il se dresse.",
  "On l'enfile avant de sortir.",
  "Il faut le faire rentrer par le petit trou.",
  "Ça se mange avec les doigts et on se lèche après.",
  "On le fait mieux quand on a de l'expérience.",
  "C'est plus facile avec un peu d'aide.",
  "On attend que ça sorte tout blanc.",
  "Ça se fait en rythme.",
  "On adore quand c'est bien juteux.",
  "Il faut appuyer sur le bouton pour que ça démarre.",
  "On le secoue et ça part tout seul.",
  "On le coince entre les jambes pour mieux le tenir.",
  "Il se vide en un rien de temps.",
  "On le fait souvent le soir, en rentrant.",
  "Il faut le tenir par les deux bouts.",
  "Ça rentre en force et ça ressort en douceur.",
  "Il est tout mou tant qu'on ne l'a pas rempli.",
  "C'est meilleur quand c'est chaud et crémeux.",
  "On le fait à plusieurs, c'est plus drôle.",
  "On l'avale d'un coup sans respirer.",
  "Ça laisse des traces sur les draps.",
  "Il vaut mieux fermer la porte avant.",
  "On crie son nom à la fin.",
  "On y va doucement la première fois.",
  "On s'en met plein la bouche.",
  "Il faut bien le frotter pour qu'il brille.",
  "Ça se gonfle avec la bouche.",
  "On le retourne pour faire l'autre côté.",
  "On ne le sort que pour les grandes occasions.",
  "Plus c'est épais, plus c'est bon.",
  "Ça tient bien droit si c'est bien fait.",
  "Il faut écarter un peu pour que ça passe.",
  "On l'entend grincer toute la nuit.",
  "C'est rose, c'est doux et ça se mange.",
  "On se met dessus et on pousse fort.",
  "On le fait rouler entre ses doigts.",
  "Ça coule le long du bras.",
  "On le lèche jusqu'au bout.",
  "Il faut changer de position si ça coince.",
  "Il a un gros manche et ça impressionne.",
  "Ça tient toute la nuit si on le branche bien.",
  "On le pousse par derrière pour le faire avancer.",
  "Il faut mouiller avant de frotter.",
  "On y met la langue pour vérifier la température.",
  "Ça se fait les yeux fermés.",
  "On s'y met à deux mains.",
  "Il faut le ranger dans sa boîte après usage.",
  "On le fait trembler en appuyant dessus.",
  "Il est plus gros que ce que j'imaginais.",
  "On le glisse sous l'oreiller.",
  "Ça laisse un goût salé.",
  "On le pique et ça gicle.",
  "Il faut le faire tourner pour que ça rentre.",
  "On ne s'arrête plus une fois qu'on a commencé.",
  "C'est tout collant après.",
  "Ça se fait mieux avec un peu de musique.",
  "On en a besoin tous les matins.",
  "Il faut le mettre bien au fond.",
  "On l'a fait sur la table de la cuisine.",
  "Ça fait du bruit quand ça claque.",
  "On y va à fond sur la fin.",
  "On la sort, on la secoue, on la range.",
  "On l'attache pour qu'il ne bouge pas.",
  "On l'essaie avant de l'acheter.",
  "On se le passe de main en main.",
  "Plus on attend, plus c'est dur.",
  "On en met partout sur le visage.",
  "Ça se prend avec une paille.",
  "On le fait discrètement au bureau.",
  "On gémit un peu quand c'est trop bon.",
  "Il faut ouvrir grand et tirer la langue.",
  "On souffle, on aspire, on recommence.",
  "Il est tout chaud quand il sort du four.",
  "On le fait durer jusqu'au bout de la nuit.",
  "Il faut le garder au chaud entre les cuisses."
];

const PROMPTS_ABSURDE = [
  "Ce qu'un pingouin cache dans son frigo.",
  "La vraie raison pour laquelle les chaussettes disparaissent.",
  "Le 11e commandement, oublié en route.",
  "Ce que ton grille-pain pense de toi.",
  "Le pire nom pour un cheval de course.",
  "Ce qu'on trouve dans la poche d'un fantôme.",
  "La nouvelle épreuve olympique de 2040.",
  "Ce que murmurent les plantes vertes la nuit.",
  "Le parfum de glace que personne n'a demandé.",
  "Le métier secret des pigeons.",
  "L'avis Google d'un extraterrestre sur la Terre.",
  "L'objet le plus inutile à emporter sur une île déserte.",
  "Le slogan d'un dentifrice pour vampires.",
  "Ce que le chat fait pendant que tu dors.",
  "Le titre du prochain best-seller de ta belle-mère.",
  "La phrase à ne jamais dire à un dragon.",
  "Ce que contient vraiment la boîte noire d'un avion.",
  "Le super-pouvoir le plus décevant.",
  "Le nom du groupe de rock formé par des légumes.",
  "Ce que les escargots se racontent à la pause.",
  "Le pire cadeau de mariage.",
  "L'excuse de retard qui marche à tous les coups.",
  "Le plat signature d'un restaurant pour robots.",
  "La matière enseignée le vendredi à l'école des sorcières.",
  "Ce qu'on entend dans un coquillage si on écoute vraiment bien.",
  "Le premier message posté par un dinosaure.",
  "La règle secrète du Monopoly.",
  "Ce que ton frigo fait quand tu fermes la porte.",
  "L'application que personne ne télécharge.",
  "La vraie couleur du ciel le mardi."
];

const BOT_ANSWERS = ["Une enceinte", "Un hamster", "Mon oncle", "Une pile", "Le Wi-Fi", "Un piment", "Une fourmi", "Un aspirateur", "Un expresso", "Une chaussette", "Un grille-pain", "Le lundi", "Un raton laveur", "Une trottinette", "Le fromage", "Un parapluie", "Le chauffage", "Un pigeon", "La télécommande", "Un moustique", "Une glace", "Un sachet de thé", "Une poêle", "Un matelas gonflable", "Une enveloppe"];
const BOT_ABSURD = ["Une licorne en redressement fiscal", "Trois pigeons dans un imper", "Du Wi-Fi en poudre", "Un raton laveur ministre", "La moustache de Mamie", "Un yaourt qui a vu des choses", "Des chaussettes en grève", "Un canapé qui juge", "Le fantôme d'un croissant", "Une baguette ceinture noire"];
const BOT_NAMES = ["Robot Gérard", "Bip-Bop", "Tata Algo", "Monsieur Pixel", "Zinzin 3000", "Carla Bug", "Octet", "Gaston.exe"];

module.exports = { PROMPTS_CLASSIQUE, PROMPTS_ABSURDE, BOT_ANSWERS, BOT_ABSURD, BOT_NAMES };
